services:
  postgres:
    networks:
      - default
      - claude-net
  snc-srs:
    networks:
      - claude-net
  snc-garage:
    networks:
      - claude-net
  snc-liquidsoap:
    networks:
      - claude-net

networks:
  claude-net:
    external: true
