const { readFileSync } = require("node:fs");
const { resolve } = require("node:path");

// ── S3 Credentials ──
// Liquidsoap's s3:// protocol shells out to AWS CLI, which reads
// AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY from the environment.
// Credentials are generated by init-garage.sh and stored in .env.

function loadEnvFile() {
  try {
    const envPath = resolve(__dirname, ".env");
    const content = readFileSync(envPath, "utf8");
    const vars = {};
    for (const line of content.split("\n")) {
      const match = line.match(/^([A-Z0-9_]+)=(.*)$/);
      if (match) vars[match[1]] = match[2].replace(/^["']|["']$/g, "");
    }
    return vars;
  } catch {
    return {};
  }
}

const dotenv = loadEnvFile();

module.exports = {
  apps: [
    {
      name: "api",
      cwd: "./apps/api",
      script: "./node_modules/.bin/tsx",
      args: "watch --ignore './uploads/**' --import ./src/env.ts src/index.ts",
      interpreter: "bash",
      env: {
        NODE_ENV: "development",
        CORS_ORIGIN: "http://localhost:3080,http://localhost:3082",
      },
      // Logging
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      merge_logs: true,
      // Restart policy
      autorestart: true,
      max_restarts: 10,
      restart_delay: 1000,
    },
    {
      name: "web",
      cwd: "./apps/web",
      script: "./node_modules/.bin/vite",
      args: "--port 3001 --strictPort",
      interpreter: "bash",
      env: {
        NODE_ENV: "development",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 1000,
    },
    {
      name: "web-staging",
      cwd: "./apps/web",
      script: "./node_modules/.bin/vite",
      args: "--port 3002 --strictPort",
      interpreter: "bash",
      env: {
        NODE_ENV: "development",
        VITE_FEATURE_CONTENT: "true",
        VITE_FEATURE_CREATOR: "true",
        VITE_FEATURE_SUBSCRIPTION: "false",
        VITE_FEATURE_MERCH: "false",
        VITE_FEATURE_BOOKING: "false",
        VITE_FEATURE_DASHBOARD: "false",
        VITE_FEATURE_ADMIN: "true",
        VITE_FEATURE_EMISSIONS: "false",
        VITE_FEATURE_CALENDAR: "true",
        VITE_FEATURE_FEDERATION: "false",
        VITE_FEATURE_STREAMING: "true",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 1000,
    },
    {
      name: "liquidsoap",
      script: "/usr/bin/liquidsoap",
      args: "/workspaces/SNC/platform/liquidsoap/playout.liq",
      interpreter: "none",
      env: {
        AWS_ACCESS_KEY_ID: dotenv.S3_ACCESS_KEY_ID || "",
        AWS_SECRET_ACCESS_KEY: dotenv.S3_SECRET_ACCESS_KEY || "",
        AWS_DEFAULT_REGION: "garage",
        PLAYOUT_STREAM_KEY: dotenv.PLAYOUT_STREAM_KEY || "",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
    },
  ],
};
