module.exports = {
  apps: [
    {
      name: "api",
      cwd: "./apps/api",
      script: "./node_modules/.bin/tsx",
      args: "watch --ignore './uploads/**' --import ./src/env.ts src/index.ts",
      interpreter: "node",
      env: {
        NODE_ENV: "development",
        CORS_ORIGIN: "http://localhost:3080,http://localhost:3082",
      },
      // Logging
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      merge_logs: true,
      // Restart policy
      autorestart: true,
      max_restarts: 10,
      restart_delay: 1000,
      kill_timeout: 30000,
    },
    {
      name: "web",
      cwd: "./apps/web",
      script: "./node_modules/.bin/vite",
      args: "--port 3001 --strictPort",
      interpreter: "node",
      env: {
        NODE_ENV: "development",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 1000,
      kill_timeout: 30000,
    },
    {
      name: "web-staging",
      cwd: "./apps/web",
      script: "./node_modules/.bin/vite",
      args: "--port 3002 --strictPort",
      interpreter: "node",
      env: {
        NODE_ENV: "development",
        VITE_FEATURE_CONTENT: "true",
        VITE_FEATURE_CREATOR: "true",
        VITE_FEATURE_SUBSCRIPTION: "false",
        VITE_FEATURE_MERCH: "false",
        VITE_FEATURE_BOOKING: "false",
        VITE_FEATURE_DASHBOARD: "false",
        VITE_FEATURE_ADMIN: "true",
        VITE_FEATURE_EMISSIONS: "false",
        VITE_FEATURE_CALENDAR: "true",
        VITE_FEATURE_FEDERATION: "false",
        VITE_FEATURE_STREAMING: "true",
      },
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 1000,
    },
  ],
};
