listen 1935;
max_connections 100;
daemon off;
srs_log_tank console;

http_server {
    enabled on;
    listen 8080;
    dir /usr/local/srs/objs/nginx/html;
    crossdomain on;
}

http_api {
    enabled on;
    listen 1985;
    crossdomain on;
    raw_api {
        enabled on;
        allow_reload on;
    }
}

vhost __defaultVhost__ {
    hls {
        enabled on;
        hls_fragment 2;
        hls_window 10;
    }

    http_hooks {
        enabled on;
        on_publish http://host.docker.internal:3000/api/streaming/callbacks/on-publish;
        on_unpublish http://host.docker.internal:3000/api/streaming/callbacks/on-unpublish;
    }

    forward {
        enabled on;
        backend http://host.docker.internal:3000/api/streaming/callbacks/on-forward;
    }
}
