import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { and, eq } from "drizzle-orm";
import { AppError, ok, err } from "@snc/shared";
import type { Result } from "@snc/shared";

import { db } from "../db/connection.js";
import { channels } from "../db/schema/streaming.schema.js";
import { config } from "../config.js";
import { rootLogger } from "../logging/logger.js";

// ── Types ──

interface PlayoutChannelRow {
  readonly id: string;
  readonly name: string;
  readonly srsStreamName: string;
}

// ── Config Path ──

/** Path to the Liquidsoap config file (mounted volume). */
const getLiquidsoapConfigPath = (): string =>
  resolve(
    config.LIQUIDSOAP_CONFIG_DIR ?? "/workspaces/SNC/platform/liquidsoap",
    "playout.liq",
  );

// ── Logger ──

const logger = rootLogger.child({ service: "liquidsoap-config" });

// ── Private Helpers ──

/** Escape a string for use in Liquidsoap string literals. */
const escLiq = (s: string): string => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');

/** Convert a UUID to a valid Liquidsoap identifier (replace hyphens with underscores, prefix with `ch_`). */
const liqId = (id: string): string => `ch_${id.replaceAll("-", "_")}`;

/** Generate the Liquidsoap block for a single playout channel. */
const renderChannelBlock = (
  ch: PlayoutChannelRow,
  opts: { apiHost: string; apiPort: string; callbackSecret: string; srsHost: string; streamKey: string },
): string => {
  const vid = liqId(ch.id);
  return `
# ── Channel: ${escLiq(ch.name)} (playout) ──

${vid}_queue = request.queue(id="channel-${ch.id}")
${vid}_source = fallback(track_sensitive=false, [${vid}_queue, mksafe(blank())])

${vid}_uri = ref("")
${vid}_title = ref("")
${vid}_source.on_metadata(synchronous=false, fun(m) -> begin
  u = m["s3_uri"]
  ${vid}_uri := if u == "" then m["filename"] else u end
  ${vid}_title := m["title"]
  ignore(http.post(
    headers=[("Content-Type", "application/json")],
    data='{"uri":"#{${vid}_uri()}","title":"#{${vid}_title()}"}',
    "http://#{api_host}:#{api_port}/api/playout/channels/${ch.id}/track-event?secret=#{callback_secret}"
  ))
end)

output.url(url="rtmp://#{srs_host}:1935/live/${escLiq(ch.srsStreamName)}?key=#{playout_key}", enc, ${vid}_source)

harbor.http.register(port=8888, method="POST", "/channels/${ch.id}/queue", fun(req, res) -> begin
  ${vid}_queue.push.uri(req.body())
  res.data("queued")
end)

harbor.http.register(port=8888, method="POST", "/channels/${ch.id}/skip", fun(_req, res) -> begin
  ${vid}_source.skip()
  res.data("skipped")
end)

harbor.http.register(port=8888, method="GET", "/channels/${ch.id}/now-playing", fun(_req, res) -> begin
  e = ${vid}_source.elapsed()
  r = ${vid}_source.remaining()
  safe_elapsed = if e == infinity or e != e then -1. else e end
  safe_remaining = if r == infinity or r != r then -1. else r end
  res.json({
    uri = ${vid}_uri(),
    title = ${vid}_title(),
    elapsed = safe_elapsed,
    remaining = safe_remaining
  })
end)
`;
};

// ── Public API ──

/**
 * Generate the full playout.liq content from database state.
 * Returns the file content as a string.
 */
export const generateLiquidsoapConfig = async (): Promise<string> => {
  const playoutChannels = await db
    .select({
      id: channels.id,
      name: channels.name,
      srsStreamName: channels.srsStreamName,
    })
    .from(channels)
    .where(
      and(
        eq(channels.type, "playout"),
        eq(channels.isActive, true),
      ),
    );

  logger.info({ channelCount: playoutChannels.length }, "Generating Liquidsoap config");

  const opts = {
    apiHost: config.LIQUIDSOAP_CALLBACK_HOST ?? "snc-api",
    apiPort: config.LIQUIDSOAP_CALLBACK_PORT ?? "3000",
    callbackSecret: config.PLAYOUT_CALLBACK_SECRET ?? "",
    srsHost: config.SRS_RTMP_HOST ?? "snc-srs",
    streamKey: config.PLAYOUT_STREAM_KEY ?? "",
  };

  // Find the first playout channel for S/NC TV fallback (static for now)
  const defaultPlayout = playoutChannels[0];
  const defaultPlayoutSourceRef = defaultPlayout
    ? `${liqId(defaultPlayout.id)}_source`
    : "mksafe(blank())";

  const channelBlocks = playoutChannels.map((ch) => renderChannelBlock(ch, opts)).join("\n");

  return `# ── Auto-generated by S/NC Platform ──
# Do not edit manually — regenerated on channel create/delete.
# Static sections (logging, S3, encoding, health, S/NC TV) are preserved.

# ── Logging ──

log.stdout := true
log.file := false
log.level := 4

# ── S3 Protocol (Garage) ──

settings.protocol.aws.endpoint := environment.get("AWS_ENDPOINT", default="http://snc-garage:3900")
settings.protocol.aws.region := environment.get("AWS_DEFAULT_REGION", default="garage")

# ── Config ──

playout_key = environment.get("PLAYOUT_STREAM_KEY", default="")
srs_host = environment.get("SRS_RTMP_HOST", default="snc-srs")
api_host = environment.get("API_CALLBACK_HOST", default="snc-api")
api_port = environment.get("API_CALLBACK_PORT", default="3000")
callback_secret = environment.get("PLAYOUT_CALLBACK_SECRET", default="")

# ── Encoding ──

enc = %ffmpeg(
  format="flv",
  %video(codec="libx264", preset="ultrafast", b="2500k", g="60"),
  %audio(codec="aac", b="128k")
)

settings.harbor.bind_addrs := ["0.0.0.0"]

# ── Health Check ──

harbor.http.register(port=8888, method="GET", "/health", fun(_req, res) -> begin
  res.data("ok")
end)

# ── Admin Control ──

harbor.http.register(port=8888, method="POST", "/admin/shutdown", fun(req, res) -> begin
  secret = environment.get("PLAYOUT_CALLBACK_SECRET", default="")
  q = req.query
  if q["secret"] == secret and secret != "" then
    res.data("shutting down")
    shutdown()
  else
    res.status_code(401)
    res.data("unauthorized")
  end
end)

# ── Playout Channels (generated from database) ──
${channelBlocks}
# ── S/NC TV (broadcast — static) ──

live_source = input.rtmp(listen=true, "rtmp://0.0.0.0:1936/live/stream")
snc_tv_queue = request.queue(id="snc-tv-queue")

snc_tv = fallback(track_sensitive=false, [live_source, snc_tv_queue, ${defaultPlayoutSourceRef}, mksafe(blank())])

snc_tv_uri = ref("")
snc_tv_title = ref("")
snc_tv.on_metadata(synchronous=false, fun(m) -> begin
  u = m["s3_uri"]
  snc_tv_uri := if u == "" then m["filename"] else u end
  snc_tv_title := m["title"]
end)

snc_tv_stream = environment.get("CHANNEL_SNCTV_STREAM", default="snc-tv")
output.url(url="rtmp://#{srs_host}:1935/live/#{snc_tv_stream}?key=#{playout_key}", enc, snc_tv)

harbor.http.register(port=8888, method="GET", "/now-playing", fun(_req, res) -> begin
  e = snc_tv.elapsed()
  r = snc_tv.remaining()
  safe_elapsed = if e == infinity or e != e then -1. else e end
  safe_remaining = if r == infinity or r != r then -1. else r end
  res.json({
    uri = snc_tv_uri(),
    title = snc_tv_title(),
    elapsed = safe_elapsed,
    remaining = safe_remaining
  })
end)
`;
};

/**
 * Write generated config to disk and signal Liquidsoap to restart.
 * Returns ok on success, err if write or restart signal fails.
 */
export const regenerateAndRestart = async (): Promise<Result<void, AppError>> => {
  const configPath = getLiquidsoapConfigPath();

  try {
    const configContent = await generateLiquidsoapConfig();
    await writeFile(configPath, configContent, "utf-8");
    logger.info({ path: configPath }, "Liquidsoap config written");
  } catch (e) {
    logger.error({ error: e instanceof Error ? e.message : String(e) }, "Failed to write Liquidsoap config");
    return err(new AppError("CONFIG_WRITE_FAILED", "Failed to write playout config", 500));
  }

  // Signal Liquidsoap to restart via harbor shutdown endpoint
  const baseUrl = config.LIQUIDSOAP_API_URL;
  if (!baseUrl) {
    logger.warn("LIQUIDSOAP_API_URL not configured — config written but restart not signaled");
    return ok(undefined);
  }

  try {
    const secret = config.PLAYOUT_CALLBACK_SECRET ?? "";
    const res = await fetch(`${baseUrl}/admin/shutdown?secret=${encodeURIComponent(secret)}`, {
      method: "POST",
      signal: AbortSignal.timeout(5000),
    });
    // Liquidsoap may close the connection before responding (shutdown is immediate)
    // Both 200 and connection reset are acceptable
    if (res.ok) {
      logger.info("Liquidsoap shutdown signaled — container will restart with new config");
    }
  } catch (e) {
    // Connection reset is expected — shutdown kills the process
    const msg = e instanceof Error ? e.message : String(e);
    if (msg.includes("fetch failed") || msg.includes("ECONNRESET") || msg.includes("ECONNREFUSED")) {
      logger.info("Liquidsoap shutdown signaled (connection closed)");
    } else {
      logger.error({ error: msg }, "Failed to signal Liquidsoap restart");
      return err(new AppError("RESTART_SIGNAL_FAILED", "Failed to signal playout engine restart", 502));
    }
  }

  return ok(undefined);
};

/**
 * Write the generated config to disk without signaling a restart.
 * Used on API startup — Liquidsoap reads the file on its own startup.
 */
export const writeConfigOnly = async (): Promise<void> => {
  const configPath = getLiquidsoapConfigPath();
  try {
    const configContent = await generateLiquidsoapConfig();
    await writeFile(configPath, configContent, "utf-8");
    logger.info({ path: configPath }, "Liquidsoap config written on startup");
  } catch (e) {
    logger.error({ error: e instanceof Error ? e.message : String(e) }, "Failed to write Liquidsoap config on startup");
    // Non-fatal — API continues without restarting Liquidsoap
  }
};

/**
 * Wait for Liquidsoap to become healthy after restart.
 * Polls the health endpoint up to maxAttempts times.
 */
export const waitForHealth = async (
  maxAttempts = 10,
  intervalMs = 2000,
): Promise<boolean> => {
  const baseUrl = config.LIQUIDSOAP_API_URL;
  if (!baseUrl) return true; // No Liquidsoap configured — vacuously healthy

  for (let i = 0; i < maxAttempts; i++) {
    try {
      const res = await fetch(`${baseUrl}/health`, {
        signal: AbortSignal.timeout(2000),
      });
      if (res.ok) return true;
    } catch {
      // Not ready yet
    }
    await new Promise((r) => setTimeout(r, intervalMs));
  }
  return false;
};
