import type {
  EnvRef,
  PlayoutChannelTopology,
  PlayoutTopology,
} from "./playout-topology.js";

// ── Private Helpers ──

/** Escape a string for use in Liquidsoap string literals. */
const escLiq = (s: string): string => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');

/** Render a runtime env reference as a Liquidsoap environment.get expression. */
const envGet = (ref: EnvRef): string =>
  `environment.get("${ref.envVar}", default="${escLiq(ref.default)}")`;

/** Render the Liquidsoap block for a single playout channel. */
const renderChannelBlock = (t: PlayoutTopology, ch: PlayoutChannelTopology): string => {
  const vid = ch.liqVar;
  return `
# ── Channel: ${escLiq(ch.name)} (playout) ──

${vid}_queue = request.queue(id="${ch.queueId}")
${vid}_source = fallback(track_sensitive=false, [${vid}_queue, mksafe(blank())])

${vid}_uri = ref("")
${vid}_title = ref("")
${vid}_queue.on_metadata(synchronous=false, fun(m) -> begin
  u = m["s3_uri"]
  ${vid}_uri := if u == "" then m["filename"] else u end
  ${vid}_title := m["title"]
  ignore(http.post(
    headers=[("Content-Type", "application/json")],
    data='{"uri":"#{${vid}_uri()}","title":"#{${vid}_title()}"}',
    "http://#{api_host}:#{api_port}${ch.trackEventPath}?secret=#{callback_secret}"
  ))
end)

output.url(url="rtmp://#{srs_host}:${t.srsRtmpPort}/live/${escLiq(ch.srsStreamName)}?key=#{playout_key}", enc, ${vid}_source)

harbor.http.register(port=${t.harborPort}, method="POST", "${ch.harborPaths.queue}", fun(req, res) -> begin
  ${vid}_queue.push.uri(req.body())
  res.data("queued")
end)

harbor.http.register(port=${t.harborPort}, method="POST", "${ch.harborPaths.skip}", fun(_req, res) -> begin
  ${vid}_source.skip()
  res.data("skipped")
end)

harbor.http.register(port=${t.harborPort}, method="GET", "${ch.harborPaths.nowPlaying}", fun(_req, res) -> begin
  e = ${vid}_source.elapsed()
  r = ${vid}_source.remaining()
  safe_elapsed = if e == infinity or e != e then -1. else e end
  safe_remaining = if r == infinity or r != r then -1. else r end
  res.json({
    uri = ${vid}_uri(),
    title = ${vid}_title(),
    elapsed = safe_elapsed,
    remaining = safe_remaining
  })
end)
`;
};

// ── Public API ──

/**
 * Render the full playout.liq content from a topology document. Pure — the
 * topology is the only input; byte-identical output for identical topologies.
 *
 * Runtime values (stream key, hosts, secrets) render as environment.get
 * references resolved by Liquidsoap in its own container, never here.
 */
export const renderPlayoutLiq = (t: PlayoutTopology): string => {
  const channelBlocks = t.channels.map((ch) => renderChannelBlock(t, ch)).join("\n");

  return `# ── Auto-generated by S/NC Platform ──
# Do not edit manually — regenerated on channel create/delete.
# Static sections (logging, S3, encoding, health, S/NC TV) are preserved.

# ── Logging ──

log.stdout := true
log.file := false
log.level := 4

# ── S3 Protocol (Garage) ──

settings.protocol.aws.endpoint := ${envGet(t.env.awsEndpoint)}
settings.protocol.aws.region := ${envGet(t.env.awsRegion)}

# ── Config ──

playout_key = ${envGet(t.env.playoutKey)}
srs_host = ${envGet(t.env.srsHost)}
api_host = ${envGet(t.env.apiHost)}
api_port = ${envGet(t.env.apiPort)}
callback_secret = ${envGet(t.env.callbackSecret)}

# ── Encoding ──

enc = %ffmpeg(
  format="flv",
  %video(codec="libx264", preset="ultrafast", b="2500k", g="60"),
  %audio(codec="aac", b="256k")
)

settings.harbor.bind_addrs := ["0.0.0.0"]

# ── Health Check ──

harbor.http.register(port=${t.harborPort}, method="GET", "/health", fun(_req, res) -> begin
  res.data("ok")
end)

# ── Admin Control ──

harbor.http.register(port=${t.harborPort}, method="POST", "/admin/shutdown", fun(req, res) -> begin
  secret = ${envGet(t.env.callbackSecret)}
  q = req.query
  if q["secret"] == secret and secret != "" then
    res.data("shutting down")
    shutdown()
  else
    res.status_code(401)
    res.data("unauthorized")
  end
end)

# ── Playout Channels (generated from database) ──
${channelBlocks}
# ── S/NC TV (broadcast — static) ──

live_source = input.rtmp(listen=true, "rtmp://0.0.0.0:${t.broadcastInputPort}/live/stream")
snc_tv_queue = request.queue(id="${t.broadcast.queueId}")

snc_tv = fallback(track_sensitive=false, [live_source, snc_tv_queue, ${t.broadcast.fallbackSourceVar}, mksafe(blank())])

snc_tv_uri = ref("")
snc_tv_title = ref("")
snc_tv.on_metadata(synchronous=false, fun(m) -> begin
  u = m["s3_uri"]
  snc_tv_uri := if u == "" then m["filename"] else u end
  snc_tv_title := m["title"]
end)

snc_tv_stream = ${envGet(t.env.sncTvStream)}
output.url(url="rtmp://#{srs_host}:${t.srsRtmpPort}/live/#{snc_tv_stream}?key=#{playout_key}", enc, snc_tv)

harbor.http.register(port=${t.harborPort}, method="GET", "/now-playing", fun(_req, res) -> begin
  e = snc_tv.elapsed()
  r = snc_tv.remaining()
  safe_elapsed = if e == infinity or e != e then -1. else e end
  safe_remaining = if r == infinity or r != r then -1. else r end
  res.json({
    uri = snc_tv_uri(),
    title = snc_tv_title(),
    elapsed = safe_elapsed,
    remaining = safe_remaining
  })
end)
`;
};
