import { describe, it, expect, vi, afterEach } from "vitest";

import { makeTestConfig } from "../helpers/test-constants.js";

// ── Mock State ──

const mockDbSelect = vi.fn();
const mockFetch = vi.fn();

// ── Setup Factory ──

const setupModule = async (overrides?: Parameters<typeof makeTestConfig>[0]) => {
  vi.stubGlobal("fetch", mockFetch);

  vi.doMock("../../src/config.js", () => ({
    config: makeTestConfig(overrides),
  }));

  vi.doMock("../../src/db/connection.js", () => ({
    db: {
      select: mockDbSelect,
    },
  }));

  vi.doMock("../../src/db/schema/streaming.schema.js", () => ({
    channels: {
      id: "id",
      name: "name",
      type: "type",
      srsStreamName: "srsStreamName",
      isActive: "isActive",
    },
  }));

  vi.doMock("../../src/logging/logger.js", () => ({
    rootLogger: {
      child: vi.fn().mockReturnValue({
        info: vi.fn(),
        warn: vi.fn(),
        error: vi.fn(),
      }),
    },
  }));

  return await import("../../src/services/liquidsoap-config.js");
};

// ── DB Chain Helper ──

const makeDbChain = (rows: unknown[]) => {
  const chain = {
    from: vi.fn().mockReturnThis(),
    where: vi.fn().mockResolvedValue(rows),
  };
  mockDbSelect.mockReturnValue(chain);
  return chain;
};

afterEach(() => {
  vi.resetModules();
  vi.unstubAllGlobals();
  vi.resetAllMocks();
});

// ── Tests ──

describe("generateLiquidsoapConfig", () => {
  it("generates valid config with channel blocks", async () => {
    const { generateLiquidsoapConfig } = await setupModule();

    makeDbChain([
      { id: "903e6a20-0dea-42b1-8dd5-86afbec496ac", name: "Classics", srsStreamName: "channel-classics" },
    ]);

    const config = await generateLiquidsoapConfig();

    // Header comment
    expect(config).toContain("Auto-generated by S/NC Platform");

    // Channel block present
    expect(config).toContain("# ── Channel: Classics (playout) ──");

    // UUID with hyphens replaced by underscores, prefixed with underscore
    expect(config).toContain("_903e6a20_0dea_42b1_8dd5_86afbec496ac_queue");
    expect(config).toContain("_903e6a20_0dea_42b1_8dd5_86afbec496ac_source");

    // Harbor endpoints use the original UUID (with hyphens) in the URL path
    expect(config).toContain("/channels/903e6a20-0dea-42b1-8dd5-86afbec496ac/queue");
    expect(config).toContain("/channels/903e6a20-0dea-42b1-8dd5-86afbec496ac/skip");
    expect(config).toContain("/channels/903e6a20-0dea-42b1-8dd5-86afbec496ac/now-playing");

    // output.url with srsStreamName
    expect(config).toContain("channel-classics");

    // Static sections
    expect(config).toContain("harbor.http.register(port=8888, method=\"GET\", \"/health\"");
    expect(config).toContain("harbor.http.register(port=8888, method=\"POST\", \"/admin/shutdown\"");

    // S/NC TV references first channel source as fallback
    expect(config).toContain("_903e6a20_0dea_42b1_8dd5_86afbec496ac_source");
    expect(config).toContain("snc_tv = fallback");
  });

  it("generates config with no channels — S/NC TV falls back to mksafe(blank())", async () => {
    const { generateLiquidsoapConfig } = await setupModule();

    makeDbChain([]);

    const config = await generateLiquidsoapConfig();

    expect(config).toContain("Auto-generated by S/NC Platform");
    // S/NC TV fallback is mksafe(blank()) when no playout channels exist
    expect(config).toContain("snc_tv = fallback(track_sensitive=false, [live_source, snc_tv_queue, mksafe(blank()), mksafe(blank())])");
    // No channel blocks
    expect(config).not.toContain("request.queue(id=\"channel-");
  });

  it("generates config with multiple channels", async () => {
    const { generateLiquidsoapConfig } = await setupModule();

    makeDbChain([
      { id: "aaaaaaaa-0000-0000-0000-000000000001", name: "Channel A", srsStreamName: "channel-a" },
      { id: "bbbbbbbb-0000-0000-0000-000000000002", name: "Channel B", srsStreamName: "channel-b" },
    ]);

    const config = await generateLiquidsoapConfig();

    expect(config).toContain("# ── Channel: Channel A (playout) ──");
    expect(config).toContain("# ── Channel: Channel B (playout) ──");
    expect(config).toContain("_aaaaaaaa_0000_0000_0000_000000000001_queue");
    expect(config).toContain("_bbbbbbbb_0000_0000_0000_000000000002_queue");

    // S/NC TV uses first channel as fallback
    expect(config).toContain("_aaaaaaaa_0000_0000_0000_000000000001_source");
  });

  it("escapes channel names with special characters in comments", async () => {
    const { generateLiquidsoapConfig } = await setupModule();

    makeDbChain([
      { id: "aaaaaaaa-0000-0000-0000-000000000001", name: 'Channel "Special" \\ Test', srsStreamName: "channel-special" },
    ]);

    const config = await generateLiquidsoapConfig();

    // Name is escaped for use in Liquidsoap string context
    expect(config).toContain('Channel \\"Special\\" \\\\ Test');
  });

  it("includes shutdown endpoint", async () => {
    const { generateLiquidsoapConfig } = await setupModule();

    makeDbChain([]);

    const config = await generateLiquidsoapConfig();

    expect(config).toContain("/admin/shutdown");
    expect(config).toContain("shutdown()");
  });
});

describe("regenerateAndRestart", () => {
  it("returns err when writeFile fails", async () => {
    // Mock fs/promises to throw
    vi.doMock("node:fs/promises", () => ({
      writeFile: vi.fn().mockRejectedValue(new Error("EACCES: permission denied")),
    }));

    const { regenerateAndRestart } = await setupModule();
    makeDbChain([]);

    const result = await regenerateAndRestart();

    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.error.code).toBe("CONFIG_WRITE_FAILED");
      expect(result.error.statusCode).toBe(500);
    }
  });

  it("returns ok and skips restart when LIQUIDSOAP_API_URL is not set", async () => {
    vi.doMock("node:fs/promises", () => ({
      writeFile: vi.fn().mockResolvedValue(undefined),
    }));

    const { regenerateAndRestart } = await setupModule({ LIQUIDSOAP_API_URL: undefined });
    makeDbChain([]);

    const result = await regenerateAndRestart();

    expect(result.ok).toBe(true);
    expect(mockFetch).not.toHaveBeenCalled();
  });

  it("returns ok when Liquidsoap shuts down (connection reset)", async () => {
    vi.doMock("node:fs/promises", () => ({
      writeFile: vi.fn().mockResolvedValue(undefined),
    }));

    mockFetch.mockRejectedValue(new Error("fetch failed: ECONNRESET"));

    const { regenerateAndRestart } = await setupModule({
      LIQUIDSOAP_API_URL: "http://localhost:8888",
    });
    makeDbChain([]);

    const result = await regenerateAndRestart();

    expect(result.ok).toBe(true);
  });

  it("returns ok when Liquidsoap responds with 200", async () => {
    vi.doMock("node:fs/promises", () => ({
      writeFile: vi.fn().mockResolvedValue(undefined),
    }));

    mockFetch.mockResolvedValue({ ok: true, status: 200 });

    const { regenerateAndRestart } = await setupModule({
      LIQUIDSOAP_API_URL: "http://localhost:8888",
    });
    makeDbChain([]);

    const result = await regenerateAndRestart();

    expect(result.ok).toBe(true);
  });
});

describe("waitForHealth", () => {
  it("returns true when LIQUIDSOAP_API_URL is not configured", async () => {
    const { waitForHealth } = await setupModule({ LIQUIDSOAP_API_URL: undefined });

    const result = await waitForHealth(1, 0);
    expect(result).toBe(true);
  });

  it("returns true when health check succeeds on first attempt", async () => {
    mockFetch.mockResolvedValue({ ok: true, status: 200 });

    const { waitForHealth } = await setupModule({
      LIQUIDSOAP_API_URL: "http://localhost:8888",
    });

    const result = await waitForHealth(3, 0);
    expect(result).toBe(true);
  });

  it("returns false when health check never succeeds", async () => {
    mockFetch.mockRejectedValue(new Error("ECONNREFUSED"));

    const { waitForHealth } = await setupModule({
      LIQUIDSOAP_API_URL: "http://localhost:8888",
    });

    const result = await waitForHealth(2, 0);
    expect(result).toBe(false);
  });
});
