#!/usr/bin/env bash
# Validate Drizzle migration artifacts for correctness.
# Catches hand-written migrations before they reach production.
#
# Usage: bash scripts/validate-migrations.sh
# Exit code: 0 = all valid, 1 = violations found

set -euo pipefail

MIGRATIONS_DIR="apps/api/drizzle/migrations"
META_DIR="$MIGRATIONS_DIR/meta"
JOURNAL="$META_DIR/_journal.json"
ERRORS=0

# Resolve paths relative to platform/ if run from repo root
if [ ! -d "$MIGRATIONS_DIR" ] && [ -d "platform/$MIGRATIONS_DIR" ]; then
  MIGRATIONS_DIR="platform/$MIGRATIONS_DIR"
  META_DIR="$MIGRATIONS_DIR/meta"
  JOURNAL="$META_DIR/_journal.json"
fi

if [ ! -f "$JOURNAL" ]; then
  echo "FAIL: _journal.json not found at $JOURNAL"
  exit 1
fi

echo "Validating migrations in $MIGRATIONS_DIR..."

# Check 1: Every SQL file has a corresponding snapshot
for sql_file in "$MIGRATIONS_DIR"/[0-9]*.sql; do
  [ -f "$sql_file" ] || continue
  idx=$(basename "$sql_file" | grep -oP '^\d+')
  snapshot="$META_DIR/${idx}_snapshot.json"
  if [ ! -f "$snapshot" ]; then
    echo "FAIL: Missing snapshot for $(basename "$sql_file") — expected $snapshot"
    ERRORS=$((ERRORS + 1))
  fi
done

# Check 2: Every journal entry has a matching SQL file
entries=$(node -e "
  const j = require('./$JOURNAL');
  j.entries.forEach(e => console.log(e.tag + '|' + e.when));
")

while IFS='|' read -r tag when; do
  [ -z "$tag" ] && continue

  # Check SQL file exists
  if [ ! -f "$MIGRATIONS_DIR/$tag.sql" ]; then
    echo "FAIL: Journal references $tag.sql but file is missing"
    ERRORS=$((ERRORS + 1))
  fi

  # Check 3: Timestamps have millisecond noise (not round numbers ending in 000000)
  if [[ "$when" =~ 000000$ ]]; then
    echo "FAIL: Fabricated timestamp for $tag — $when ends in 000000"
    ERRORS=$((ERRORS + 1))
  fi

  # Check 4: Filenames follow drizzle-kit's pattern (NNNN_word_word or NNNN_word_word_word)
  name_part=$(echo "$tag" | sed 's/^[0-9]*_//')
  if echo "$name_part" | grep -qP '[A-Z]'; then
    echo "FAIL: Migration name '$tag' contains uppercase — likely hand-written"
    ERRORS=$((ERRORS + 1))
  fi
  # Descriptive names like "add_creator_id_to_calendar_events" have 4+ words
  word_count=$(echo "$name_part" | tr '_' '\n' | wc -l)
  if [ "$word_count" -gt 3 ]; then
    echo "WARN: Migration name '$tag' has $word_count words — drizzle-kit typically generates 2-3 word names"
  fi

done <<< "$entries"

# Check 5: SQL files use standard statement breakpoint markers
for sql_file in "$MIGRATIONS_DIR"/[0-9]*.sql; do
  [ -f "$sql_file" ] || continue
  # Check for non-standard breakpoint markers (e.g. ----- instead of -->)
  if grep -q 'statement-breakpoint' "$sql_file" && ! grep -q -- '--> statement-breakpoint' "$sql_file"; then
    # File has breakpoints but none use --> format — all are non-standard
    if ! grep -q '^-- Custom SQL migration file' "$sql_file"; then
      echo "WARN: $(basename "$sql_file") uses non-standard statement breakpoint markers"
    fi
  fi
done

if [ "$ERRORS" -gt 0 ]; then
  echo ""
  echo "FAILED: $ERRORS violation(s) found. Migrations must be generated by drizzle-kit, not hand-written."
  echo "See .claude/rules/drizzle-migrations.md for the correct workflow."
  exit 1
else
  echo "OK: All migrations are valid."
  exit 0
fi
